/* ------------------------------------------------------------------ */
/*  Purchase Request Creation Service                                 */
/*  Formal entry point for creating new PurchaseRequests.             */
/* ------------------------------------------------------------------ */

import type { PurchaseRequest, RequestItem } from '../types';
import { createAuditLogBase } from '../config/auditDefaults';
import { auditStore } from './auditStore';
import { purchaseRequestStore } from './purchaseRequestStore';
import { assertCan } from '../core/security/policyEngine';
import { getActor } from '../stores/authStore';

/* ------------------------------------------------------------------ */
/*  Input type — minimal data the caller must provide                 */
/* ------------------------------------------------------------------ */

export interface CreatePurchaseRequestInput {
  /** Target warehouse code */
  wh: string;
  /** Line items (may be empty for portal / manual drafts) */
  items: RequestItem[];
  /** How the request originated */
  origin?: 'Manual' | 'Excel' | 'Portal';
  /** Recipient e-mail for portal-type requests */
  recipientEmail?: string;
  /** Secure-link token (generated by caller or service) */
  token?: string;
}

/* ------------------------------------------------------------------ */
/*  ID helpers                                                        */
/* ------------------------------------------------------------------ */

let _seqCounter = 0;

function generateId(): string {
  _seqCounter += 1;
  return (
    'REQ-' +
    new Date().getFullYear() +
    '-' +
    String(_seqCounter).padStart(3, '0')
  );
}

/** Allow the UI (or tests) to seed the counter so IDs stay sequential
 *  with existing data loaded from localStorage.
 */
export function seedIdCounter(existingCount: number): void {
  _seqCounter = existingCount;
}

/* ------------------------------------------------------------------ */
/*  Service function                                                  */
/* ------------------------------------------------------------------ */

/**
 * Creates a new PurchaseRequest from minimal input, persists it in the
 * store, and records an audit log entry.
 *
 * Responsibilities handled by the service (callers must NOT set these):
 *  - id           → auto-generated
 *  - companyId    → stamped from authenticated actor
 *  - createdBy    → stamped from authenticated actor
 *  - status       → always 'draft'
 *  - createdAt    → current date
 *
 * @param input  Minimal creation payload.
 * @returns The fully-built, persisted PurchaseRequest.
 */
export function createPurchaseRequest(
  input: CreatePurchaseRequestInput,
): PurchaseRequest {
  const actor = getActor();
  assertCan(actor, 'PR_CREATE');

  const id = generateId();
  const now = new Date().toISOString().split('T')[0];

  const request: PurchaseRequest = {
    id,
    companyId: actor.companyId,
    createdBy: actor.userId,
    wh: input.wh,
    status: 'draft',
    createdAt: now,
    items: input.items,
    origin: input.origin,
    recipientEmail: input.recipientEmail,
    token: input.token,
  };

  const exists = purchaseRequestStore
    .getState()
    .purchaseRequests.find((r) => r.id === request.id);

  if (exists) {
    throw new Error('PurchaseRequest with this id already exists.');
  }

  purchaseRequestStore.addRequest(request);

  const log = createAuditLogBase(
    request.wh,
    'purchase_request',
    request.id,
    'created',
    actor.userId,
  );

  auditStore.addLog(log);

  return request;
}
