/* ------------------------------------------------------------------ */
/*  Purchase Request Creation Service                                 */
/*  Formal entry point for creating new PurchaseRequests.             */
/* ------------------------------------------------------------------ */

import type { PurchaseRequest, RequestItem } from '../types';
import { createAuditLogBase } from '../config/auditDefaults';
import { auditStore } from './auditStore';
import { purchaseRequestStore } from './purchaseRequestStore';
import { assertCan } from '../core/security/policyEngine';
import { getActor } from '../stores/authStore';
import { resolveWarehouseId } from '../data/warehouseMaster';

/* ------------------------------------------------------------------ */
/*  Input type — minimal data the caller must provide                 */
/* ------------------------------------------------------------------ */

export interface CreatePurchaseRequestInput {
  /** Target warehouse code */
  wh: string;
  /** Line items (may be empty for portal / manual drafts) */
  items: RequestItem[];
  /** How the request originated */
  origin?: 'manual' | 'import' | 'ai' | 'Manual' | 'Excel' | 'Portal';
  /** Recipient e-mail for portal-type requests */
  recipientEmail?: string;
  /** Secure-link token (generated by caller or service) */
  token?: string;
}

/* ------------------------------------------------------------------ */
/*  ID helpers                                                        */
/* ------------------------------------------------------------------ */

let _seqCounter = 0;

function generateId(): string {
  _seqCounter += 1;
  return (
    'REQ-' +
    new Date().getFullYear() +
    '-' +
    String(_seqCounter).padStart(3, '0')
  );
}

/** Allow the UI (or tests) to seed the counter so IDs stay sequential
 *  with existing data loaded from localStorage.
 */
export function seedIdCounter(existingCount: number): void {
  _seqCounter = existingCount;
}

/* ------------------------------------------------------------------ */
/*  Service function                                                  */
/* ------------------------------------------------------------------ */

/**
 * Creates a new PurchaseRequest from minimal input, persists it in the
 * store, and records an audit log entry.
 *
 * Responsibilities handled by the service (callers must NOT set these):
 *  - id           → auto-generated
 *  - companyId    → stamped from authenticated actor
 *  - createdBy    → stamped from authenticated actor
 *  - status       → always 'draft'
 *  - createdAt    → current date
 *
 * @param input  Minimal creation payload.
 * @returns The fully-built, persisted PurchaseRequest.
 */
export function createPurchaseRequest(
  input: CreatePurchaseRequestInput,
): PurchaseRequest {
  const actor = getActor();
  assertCan(actor, 'PR_CREATE');
  const warehouseId = resolveWarehouseId(input.wh);
  if (!warehouseId) {
    throw new Error('WAREHOUSE_UNKNOWN');
  }

  const id = generateId();
  const now = new Date().toISOString();

  const mapOrigin = (
    origin?: CreatePurchaseRequestInput['origin'],
  ): PurchaseRequest['origin'] | undefined => {
    if (!origin) return undefined;
    if (origin === 'manual' || origin === 'import' || origin === 'ai') return origin;
    if (origin === 'Manual') return 'manual';
    if (origin === 'Excel') return 'import';
    if (origin === 'Portal') return 'ai';
    return undefined;
  };

  const request: PurchaseRequest = {
    id,
    companyId: actor.companyId,
    createdBy: actor.userId,
    warehouseId,
    wh: input.wh,
    status: 'draft',
    createdAt: now,
    version: 1,
    items: input.items,
    origin: mapOrigin(input.origin),
    recipientEmail: input.recipientEmail,
    token: input.token,
  };

  const exists = purchaseRequestStore
    .getState()
    .purchaseRequests.find((r) => r.id === request.id);

  if (exists) {
    throw new Error('PurchaseRequest with this id already exists.');
  }

  purchaseRequestStore.addRequest(request);

  const log = createAuditLogBase(
    actor.companyId,
    'purchase_request',
    request.id,
    'created',
    actor.userId,
  );

  auditStore.addLog(log);

  return request;
}
